name: Deploy Website

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/;
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key;
          sudo chmod 600 ~/.ssh/private.key;
          ssh-keyscan "$SSH_HOST" > ~/.ssh/known_hosts;
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_IP_ADDRESS }}

      - name: Test SSH
        run: |
          ssh -i ~/.ssh/private.key $SSH_USERNAME@SSH_HOST "ls -la";
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_IP_ADDRESS }}