name: Deploy Website

on: workflow_dispatch

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go 1.23.0
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Build Go
        run: |
          go build ./main.go

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/;
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key;
          sudo chmod 600 ~/.ssh/private.key;
          ssh-keyscan "$SSH_HOST" > ~/.ssh/known_hosts;
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_IP_ADDRESS }}

      - name: Copy and Start
        run: |
          ssh -i ~/.ssh/private.key $SSH_USERNAME@$SSH_HOST "ls -la";

          scp -i ~/.ssh/private.key ./main $SSH_USERNAME@$SSH_HOST:~
          scp -i ~/.ssh/private.key ./static/* $SSH_USERNAME@$SSH_HOST:~/static;
          
          ssh -i ~/.ssh/private.key $SSH_USERNAME@$SSH_HOST "./main &";
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ secrets.SSH_IP_ADDRESS }}